// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRd1UFWbiM4nlq6bmaqIq2Z0qKTIYN-WU',
    appId: '1:986195390850:web:356c0e277c9a439f341f9b',
    messagingSenderId: '986195390850',
    projectId: 'student-manager-lab',
    authDomain: 'student-manager-lab.firebaseapp.com',
    storageBucket: 'student-manager-lab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGR0puzgjfVIiRsOJx7VXA1wI-6DeVibw',
    appId: '1:986195390850:android:be30f84ff2999736341f9b',
    messagingSenderId: '986195390850',
    projectId: 'student-manager-lab',
    storageBucket: 'student-manager-lab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9aBPnnPRWActUWQKzbZ55okFem2_7BSM',
    appId: '1:986195390850:ios:2853f41079ad03be341f9b',
    messagingSenderId: '986195390850',
    projectId: 'student-manager-lab',
    storageBucket: 'student-manager-lab.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9aBPnnPRWActUWQKzbZ55okFem2_7BSM',
    appId: '1:986195390850:ios:2853f41079ad03be341f9b',
    messagingSenderId: '986195390850',
    projectId: 'student-manager-lab',
    storageBucket: 'student-manager-lab.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRd1UFWbiM4nlq6bmaqIq2Z0qKTIYN-WU',
    appId: '1:986195390850:web:3d0d8b63cf84a9c1341f9b',
    messagingSenderId: '986195390850',
    projectId: 'student-manager-lab',
    authDomain: 'student-manager-lab.firebaseapp.com',
    storageBucket: 'student-manager-lab.firebasestorage.app',
  );
}
